package:
    name:           hidev-codeception
    namespace:      hidev\codeception
    headline:       HiDev Codeception
    title:          Codeception plugin for HiDev
    type:           yii2-extension
    keywords:       codeception, hidev, plugin
    year:           2015
    description:    |
        [HiDev](https://github.com/hiqdev/hidev) is a task runner, code generator and build tool for easier continuos integration.
        This plugin enables [Codeception](http://codeception.com) support for HiDev.

        Provides usual Codeception operations:
        - bootstrapping
        - generating codeception.yml
        - generating basic unit tests (in progress)
        - running tests

require:
    hiqdev/hidev-php:           "*@dev"
    hiqdev/hidev-hiqdev:        "*@dev"
    hiqdev/hidev-license:       "*@dev"
    hiqdev/hidev-phpunit:       "*@dev"
    hiqdev/hidev-travis-ci:     "*@dev"
    hiqdev/hidev-codeception:   "*@dev"
    hiqdev/hidev-php-cs-fixer:  "*@dev"
