package:
    name:           hidev-codeception
    namespace:      hidev\codeception
    label:          HiDev Codeception
    title:          Codeception plugin for HiDev
    type:           yii2-extension
    keywords:       codeception, hidev, plugin
    year:           2015

require:
    hiqdev/hidev-config:        "*"
    hiqdev/hidev-config-php:    "*"
