package:
    type:           yii2-extension
    name:           hidev-codeception
    title:          Codeception plugin for HiDev
    headline:       HiDev Codeception
    keywords:       codeception, hidev, plugin
    namespace:      hidev\codeception
    description:    |
        [HiDev](https://github.com/hiqdev/hidev) is a task runner, code generator and build tool for easier continuos integration.
        This plugin enables [Codeception](http://codeception.com) support for HiDev.

        Provides usual Codeception operations:

        - bootstrapping
        - generating codeception.yml
        - generating basic unit tests (in progress)
        - running tests

require:
    hiqdev/hidev-php:    "*"
    hiqdev/hidev-vendor: "*"
